name: tests
on:
  push:
jobs:
  unit-tests:
    name: Testrunner unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: docker://python:3.11
        with:
          args: |
            /bin/sh -c "
            pip install .[dev] &&
            python -m pytest"